Repository honeycombio/opentelemetry-collector-configs, pull requests merged in 2022-10, with the labels that each got.

#31 maint: add new project workflow
  .github/workflows/add-to-project-v2.yml
Labels: type: maintenance, merge at will, version: no bump, no-changelog

#33 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: type: maintenance, merge at will, version: no bump

#34 Fix timestampprocessor version number to 1.4.0 in example build config
  docs/building.md
  timestampprocessor/README.md
Labels: type: documentation, version: no bump

#36 Update timeseriesprocessor to use OTEL Collector 0.63.0 libraries.
  .circleci/config.yml
  .circleci/images/Dockerfile
  .gitignore
  timestampprocessor/config.go
  timestampprocessor/config_test.go
  timestampprocessor/factory.go
  timestampprocessor/factory_test.go
  timestampprocessor/go.mod
  timestampprocessor/go.sum
  timestampprocessor/testdata/config.yaml
  timestampprocessor/testdata/config_invalid.yaml
  timestampprocessor/timestamp_processor.go
  timestampprocessor/timestamp_processor_test.go
Labels: type: maintenance, version: bump patch

#37 Bump manifest and components to use OTEL Collector 0.63.1
  .circleci/config.yml
  .circleci/images/Dockerfile
  builder-config.yaml
  docs/building.md
  timestampprocessor/go.mod
  timestampprocessor/go.sum
Labels: type: maintenance, version: bump patch
