Repository honeycombio/opentelemetry-collector-configs, pull requests merged in 2022-11, with the labels that each got.

#42 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#44 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump

#46 chore: Improve documentation
  .circleci/README.md
  README.md
  RELEASING.md
Labels: type: documentation
